router bgp 64512
 timers bgp 3 9
 bgp router-id 192.168.0.1
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax

neighbor SPINES peer-group
 neighbor SPINES remote-as external
 neighbor SPINES advertisement-interval 0
 neighbor SPINES timers connect 10
 neighbor eth0 interface peer-group SPINES
 neighbor eth1 interface peer-group SPINES

neighbor METALLB peer-group
  neighbor METALLB remote-as 65001
  bgp listen range 201.0.0.0/8 peer-group METALLB
  bgp listen limit 5000

address-family ipv4 unicast
  neighbor SPINES activate
  neighbor METALLB activate
  redistribute connected route-map LOOPBACKS
  network 201.1.1.0/24
  network 201.1.2.0/24
  network 201.1.3.0/24
  maximum-paths 64
exit-address-family

route-map LOOPBACKS permit 10
  match interface lo