apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-dply
  namespace: word-ns
spec:
  selector:
    matchLabels:
      app: word
  replicas: 2
  template:
    metadata:
      labels:
        app: word
    spec:
      containers:
      - name: word-container
        image: ik2227/drow
        ports:
        - containerPort: 5000