apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: peerings-1-1
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 64512
  peerAddress: 192.168.0.1
  ebgpMultiHop: true
  disableMP: true
  nodeSelectors:
  - matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values: [worker1, worker2]
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: peerings-1-2
  namespace: metallb-system
spec:
  myASN: 65001
  peerASN: 64513
  peerAddress: 192.168.0.2
  ebgpMultiHop: true
  disableMP: true
  nodeSelectors:
  - matchExpressions:
    - key: kubernetes.io/hostname
      operator: In
      values: [worker3, worker4, worker5]
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb-system
spec:
  avoidBuggyIPs: true
  addresses:
  - 101.0.0.0/8
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - pool