apiVersion: apps/v1
kind: Deployment
metadata:
  name: worddb-dply
  namespace: word-ns
spec:
  selector:
    matchLabels:
      app: worddb
  replicas: 1
  template:
    metadata:
      labels:
        app: worddb
    spec:
      containers:
      - name: worddb-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: worddb
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        volumeMounts:
        - name: worddb
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: worddb
        persistentVolumeClaim:
          claimName: worddb-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherdb-dply
  namespace: weather-ns
spec:
  selector:
    matchLabels:
      app: weatherdb
  replicas: 1
  template:
    metadata:
      labels:
        app: weatherdb
    spec:
      containers:
      - name: weatherdb-container
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: weatherdb
        - name: POSTGRES_USER
          value: root
        - name: POSTGRES_PASSWORD
          value: root
        volumeMounts:
        - name: weatherdb
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: weatherdb
        persistentVolumeClaim:
          claimName: weatherdb-pvc