apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: worddb-pvc
  namespace: word-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weatherdb-pvc
  namespace: weather-ns
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi
  storageClassName: ssd