apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: llm-d-pd
  namespace: llm-d
spec:
  selector:
    matchLabels:
      app: llm-d-pd
  endpointPickerRef:
    name: llm-d-epp
    kind: Service
    port:
      number: 9002
  targetPorts:
  - number: 8000
